export type ApiResponse<T = null> = {
  isSuccess: boolean;
  message: string;
  messageCode: ErrorCode | null;
  errors?: Record<string, string[]> | null;
  data: T | null;
};

export enum HttpStatusCode {
  OK = 200,

  BAD_REQUEST = 400,
  UNAUTHORIZED = 401,
  FORBIDDEN = 403,
  NOT_FOUND = 404,
  CONFLICT = 409,
  UNPROCESSABLE_ENTITY = 422,

  INTERNAL_SERVER_ERROR = 500,
  SERVICE_UNAVAILABLE = 503,

  TOO_MANY_REQUESTS = 429,
}

export enum ErrorCode {
  /* AUTH — CREDENTIALS & ACCESS */
  AUTH_INVALID_CREDENTIALS = "AUTH_INVALID_CREDENTIALS",
  AUTH_UNAUTHORIZED = "AUTH_UNAUTHORIZED",

  /* AUTH — TOKEN (JWT / SESSION) */
  AUTH_INVALID_TOKEN = "AUTH_INVALID_TOKEN",
  AUTH_TOKEN_EXPIRED = "AUTH_TOKEN_EXPIRED",
  AUTH_SESSION_REVOKED = "AUTH_SESSION_REVOKED",
  AUTH_REFRESH_TOKEN_REUSED = "AUTH_REFRESH_TOKEN_REUSED",

  /*  VALIDATION  */
  VALIDATION_FAILED = "VALIDATION_FAILED",

  /*  RESOURCE  */
  RESOURCE_NOT_FOUND = "RESOURCE_NOT_FOUND",
  RESOURCE_CONFLICT = "RESOURCE_CONFLICT",

  /*  SYSTEM  */
  INTERNAL_SERVER_ERROR = "INTERNAL_SERVER_ERROR",
  TOO_MANY_REQUESTS = "TO_MANY_REQUESTS",
}
