import { FlowStep } from "@/shared/components/ui/flow-card";

export const FLOW_STEPS: FlowStep[] = [
  {
    step: "01",
    title: "Registration",
    description: [
      "User can register with email and password (credentials)",
      "User can register with Google OAuth",
      "Password is hashed with bcrypt before storing",
      "A credentials account is created and linked to the user",
      "Duplicate email registration is rejected",
    ],
    side: "left",
    detailUrl: "",
  },
  {
    step: "02",
    title: "Login",
    description: [
      "User can login with email and password (credentials)",
      "User can login with Google OAuth",
      "Credentials are validated against the stored hashed password",
      "A credentials account is auto-created if missing on first login",
      "Google login auto-registers a new user if email is not found",
      "Invalid credentials return a generic error to prevent enumeration",
    ],
    side: "right",
    detailUrl: "",
  },
  {
    step: "03",
    title: "Sign Token",
    description: [
      "Access token is signed with HS256 and expires in 15 minutes",
      "Refresh token is signed with HS256 and expires in 7 days",
      "Access token is stored in Redis for fast session validation",
      "Refresh token is stored in the database with client and geo info",
      "Token rotation creates a new session on every refresh",
      "Old session is marked as replaced by the new session ID",
    ],
    side: "left",
    detailUrl: "",
  },
  {
    step: "04",
    title: "Email Verification",
    description: [
      "A 6-digit OTP is generated and sent to the user's email",
      "OTP is stored in Redis with a 15-minute TTL",
      "Sending OTP is rate-limited to 3 requests per 30 minutes",
      "OTP verification is rate-limited to 5 attempts per 10 minutes",
      "On success, the user's verifiedAt field is updated",
      "A new access token is issued after successful verification",
      "OTP keys are deleted from Redis after verification",
    ],
    side: "right",
    detailUrl: "",
  },
  {
    step: "05",
    title: "Session Management",
    description: [
      "User can view all active sessions",
      "User can revoke a specific session by its ID",
      "User can revoke all other sessions except the current one",
      "Replay attack detection: if a revoked refresh token is reused, all sessions are force-revoked",
      "Session chain traversal ensures all descendant sessions are revoked",
    ],
    side: "left",
    detailUrl: "",
  },
  {
    step: "06",
    title: "Change Name",
    description: [
      "User can update their display name",
      "New name cannot be the same as the current name",
      "Rate-limited to 5 requests per 15 minutes",
      "User must exist to perform the name change",
    ],
    side: "right",
    detailUrl: "",
  },
  {
    step: "07",
    title: "Change Password",
    description: [
      "User must provide the current password to change it",
      "Only available for accounts with credentials provider",
      "New password is hashed with bcrypt before storing",
      "All other sessions are revoked after password change",
      "A revert account email is sent after password change",
      "Rate-limited to 5 requests per 15 minutes",
    ],
    side: "left",
    detailUrl: "",
  },
  {
    step: "08",
    title: "2FA Verification",
    description: [
      "A 6-digit OTP is sent to the user's registered email",
      "OTP is scoped to a specific action (e.g., change password, connect provider)",
      "OTP is stored in Redis with a 15-minute TTL",
      "Sending OTP is rate-limited to 3 requests per 15 minutes",
      "Verification is rate-limited to 5 attempts per 15 minutes",
      "On success, a short-lived 2FA token is issued",
    ],
    side: "right",
    detailUrl: "",
  },
  {
    step: "09",
    title: "Send Revert Account Email",
    description: [
      "Triggered automatically after a password change",
      "A unique revert token and token ID are generated",
      "Revert token is stored in Redis with a 7-day TTL",
      "A revert link is emailed to the user's current email",
      "Rate-limited to 3 requests per 15 minutes",
    ],
    side: "left",
    detailUrl: "",
  },
  {
    step: "10",
    title: "Revert Account",
    description: [
      "User clicks the revert link received via email",
      "Revert token is validated against the stored Redis token",
      "User provides a new password to restore account access",
      "Password is updated and all active sessions are revoked",
      "Revert token keys are cleaned up from Redis after use",
    ],
    side: "right",
    detailUrl: "",
  },
  {
    step: "11",
    title: "Change Email",
    description: [
      "Only available for accounts using credentials provider",
      "New email must not be already in use by another account",
      "New email cannot be the same as the current email",
      "An email change request is created in the database",
      "Only one pending email change request is allowed at a time",
      "User can update or cancel a pending email change request",
    ],
    side: "left",
    detailUrl: "",
  },
  {
    step: "12",
    title: "2FA Verification",
    description: [
      "Required before proceeding with email change",
      "A 6-digit OTP is sent to the new email address",
      "OTP is stored in Redis with a 15-minute TTL",
      "Sending OTP is rate-limited to 3 requests per 30 minutes",
      "Verification is rate-limited to 5 attempts per 10 minutes",
      "On success, the email change request is marked as verified",
    ],
    side: "right",
    detailUrl: "",
  },
  {
    step: "13",
    title: "Verify New Email",
    description: [
      "User submits the OTP sent to the new email address",
      "OTP must match the one stored in Redis",
      "On success, the user's email is updated to the new email",
      "The user's verifiedAt timestamp is refreshed",
      "All other sessions are revoked after email update",
      "A revert account email is sent to the old email address",
    ],
    side: "left",
    detailUrl: "",
  },
  {
    step: "14",
    title: "Send Revert Account Email",
    description: [
      "Triggered automatically after a successful email change",
      "Revert email is sent to the user's old email address",
      "A unique revert token and token ID are generated",
      "Revert token is stored in Redis with a 7-day TTL",
      "Rate-limited to 3 requests per 15 minutes",
    ],
    side: "right",
    detailUrl: "",
  },
  {
    step: "15",
    title: "Revert Account",
    description: [
      "User clicks the revert link sent to the old email",
      "Revert token ID is validated against Redis",
      "Email change request record is retrieved and verified",
      "User provides a new password to restore account access",
      "Email is reverted back to the old email address",
      "All active sessions are revoked after account revert",
    ],
    side: "left",
    detailUrl: "",
  },
  {
    step: "16",
    title: "Manage OAuth Providers",
    description: [
      "User can connect a Google account to their profile",
      "User can disconnect a linked Google account",
      "User can connect a credentials provider by setting a password",
      "User can disconnect credentials by removing the password",
      "Cannot disconnect the only remaining provider",
      "Cannot disconnect the provider currently used for the session",
      "All other sessions are revoked after connecting or disconnecting a provider",
    ],
    side: "right",
    detailUrl: "",
  },
  {
    step: "17",
    title: "2FA Verification",
    description: [
      "Required before connecting or disconnecting an OAuth provider",
      "A 6-digit OTP is sent to the user's registered email",
      "OTP scope is tied to the specific action being performed",
      "OTP is stored in Redis with a 15-minute TTL",
      "Sending OTP is rate-limited to 3 requests per 15 minutes",
      "On success, a short-lived 2FA token is issued to authorize the action",
    ],
    side: "left",
    detailUrl: "",
  },
  {
    step: "18",
    title: "Logout",
    description: [
      "User can logout from the current session",
      "The session record is revoked in the database",
      "The access token is removed from Redis",
      "Auth cookies are cleared from the browser",
    ],
    side: "right",
    detailUrl: "",
  },
];
